/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2019-07-03 09:08:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.userPages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entity.*;
import utils.*;
import java.util.*;
import java.sql.*;

public final class problemDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("utils");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("entity");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
String strId=request.getParameter("q_id");//得到上一个界面的q_id
int u_id = -1;
HttpSession session1 = request.getSession();
if(session1 != null){
	if(session1.getAttribute("uid")!=null){
		u_id = (int) session1.getAttribute("uid");
	}
}
//HttpSession session1=request.getSession();
//int id2 =(int) session1.getAttribute("u_id");//得到session的值并转化成整型
int id=Integer.parseInt(strId);
//int id=1;


Class.forName(DBConn.getDRI());
Connection conn = DriverManager.getConnection(DBConn.getURL(), DBConn.getUsr(), DBConn.getPWD());


Statement stmt=conn.createStatement();
Statement stmt1=conn.createStatement();
Statement stmt2=conn.createStatement();
Statement stmt3=conn.createStatement();
Statement stmt4=conn.createStatement();
Statement stmt5=conn.createStatement();
//ResultSet rs=stmt.executeQuery("select * from article where id='"+id+"'");

ResultSet rs=stmt.executeQuery("select * from qiuwen_question where q_id="+id);//问题
ResultSet rs1=stmt1.executeQuery("select * from qiuwen_userques where q_id="+id);//提问题的用户和时间
if(rs1.next()){
	ResultSet rs2=stmt2.executeQuery("select * from qiuwen_user where usr_id="+rs1.getInt("u_id"));//提问题的用户


		


      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("\t<meta name=\"description\" content=\"Basic HTML5 App generated by MyEclipse Mobile Tools\" />\r\n");
      out.write("\t<!--引入Bootstrap-->\r\n");
      out.write("\t<link href=\"../bootstrap3.3.7/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../bootstrap3.3.7/js/bootstrap.js\"></script>\r\n");
      out.write("\t<!--引入jquery-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\t<!-- 引入外部css-->\r\n");
      out.write("\t<link href=\"../css/problemDetails.css\" rel=\"stylesheet\">\r\n");
      out.write("\t <!-- layer -->\r\n");
      out.write(" <script type=\"text/javascript\" src=\"../layer/layer.js\"></script>\r\n");
      out.write("\t<title>problemDetails</title>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t $(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("       \t$(\"button#answer\").click(function(){\r\n");
      out.write("       \t\twindow.location.href=\"questionEdit.html\"; \r\n");
      out.write("       \t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"button.login\").click(function() {\r\n");
      out.write("\t\t\t/* Act on the event */\r\n");
      out.write("\t\t\tlayer.open({\r\n");
      out.write("                   type: 2,\r\n");
      out.write("                   title: '登陆',\r\n");
      out.write("                   shadeClose: true,\r\n");
      out.write("                   shade: 0.8,\r\n");
      out.write("                   area: ['400px', '480px'],\r\n");
      out.write("                   content: 'login.html' ,\r\n");
      out.write("                  // success: function(layero,index)\r\n");
      out.write("                  // {\r\n");
      out.write("                  // \t var subm = layer.getChildFrame('#subm',index);\r\n");
      out.write("                  // \t subm.click(function(event) {\r\n");
      out.write("                  // \t layer.closeAll();\r\n");
      out.write("                  // \t });\r\n");
      out.write("                  // }\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"button.zhuce\").click(function() {\r\n");
      out.write("\t\t\t/* Act on the event */\r\n");
      out.write("\t\t\tlayer.open({\r\n");
      out.write("                   type: 2,\r\n");
      out.write("                   title: '注册',\r\n");
      out.write("                   shadeClose: true,\r\n");
      out.write("                   shade: 0.8,\r\n");
      out.write("                   area: ['400px', '480px'],\r\n");
      out.write("                   content: 'sign.html' ,\r\n");
      out.write("                   success:function(layero,index)\r\n");
      out.write("                   {\r\n");
      out.write("                   \t// layer.msg('注册成功')；\r\n");
      out.write("                   }\r\n");
      out.write("                  \r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"button.ask\").click(function() {\r\n");
      out.write("\t\t\t/* Act on the event */\r\n");
      out.write("\t\t\tlayer.open({\r\n");
      out.write("                   type: 2,\r\n");
      out.write("                   title: '问题编辑',\r\n");
      out.write("                   shadeClose: true,\r\n");
      out.write("                   shade: 0.8,\r\n");
      out.write("                   area: ['700px', '350px'],\r\n");
      out.write("                   content: 'edit.html' ,\r\n");
      out.write("                  success: function(layero,index)\r\n");
      out.write("                  {\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  \t\t// layer.msg('提交成功')\r\n");
      out.write("                  }\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("});\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-image: url(../images/back.jpg)\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
  		//ArrayList answers = (ArrayList) request.getAttribute("qiuwen_question_answer");
	while(rs.next()&rs2.next()) {
  	
      out.write("\r\n");
      out.write("\t<div class=\"header\" id=\"header\">\r\n");
      out.write("\t\t<nav class=\"navbar\" role=\"navigation\" style=\"height: 105px\">\r\n");
      out.write("\t\t   <div class=\"navbar-header\" >\r\n");
      out.write("\t\t      <img  class=\"tubiao\" src=\"../images/biao.jpg\" width=\"100\" height=\"100\" alt=\"图标\">\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container body\">\r\n");
      out.write("\t\t<div class=\"row top\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"container problemDetails\">\r\n");
      out.write("\t\t\t\t<div class=\"row block\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2 block-avatar\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"avatar\" src=\"../images/defaultTouxiang.jpg\" alt=\"头像\" width=\"100\" height=\"100\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-10 block-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row rightCol\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-9 rightOner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"color:black\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>");
      out.print(rs2.getString("usr_account") );
      out.write("</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-3 rightOner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>");
      out.print(rs.getDate("sub_time") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-2 rightOner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>");
      out.print(rs2.getString("school") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row rightCol\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>");
      out.print(rs.getString("q_text") );
      out.write(" </p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row rightCol\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<object data=\"icon/commit.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+");
      out.print(rs.getInt("follow"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<object data=\"icon/aixin.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+");
      out.print(rs.getInt("click_num") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<object data=\"icon/jubao.svg\" width=\"300\" height=\"300\" type=\"image/svg+xml\" codebase=\"http://www.adobe.com/svg/viewer/imstall/\"></object>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    ");
      out.print(rs.getString("category") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(basePath);
      out.write("/userPages/questionEdit.jsp?q_id=");
      out.print(rs.getInt("q_id"));
      out.write("\"><button id=\"answer\" class=\"btn btn-info btn-sm\" style=\"");
      out.print( u_id == -1 ? "display:none":"" );
      out.write("\"> 我要回答</button>\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

		ResultSet rs3=stmt3.executeQuery("select * from qiuwen_quesanswer where q_id="+id);//回答
		while(rs3.next()){
			ResultSet rs4=stmt4.executeQuery("select * from qiuwen_user where usr_id="+rs3.getInt("u_id"));//回答的用户
			if(rs4.next()){
			
      out.write("\r\n");
      out.write("\t<div class=\"container body\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"container problemDetails\">\r\n");
      out.write("\t\t\t\t<div class=\"row block2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 block-avatar\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"avatar\" src=\"../images/profile.jpg\" alt=\"头像\" width=\"100\" height=\"100\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-10 block-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row center col-md-10 block-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"float:left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p style=\"color:black\">");
      out.print(rs4.getString("usr_account") );
      out.write("：</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"float:left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p> ");
      out.print(rs3.getDate("ans_time") );
      out.write(' ');
      out.print(rs4.getString("school") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row col2 block3 \">\r\n");
      out.write("\t\t\t\t<p>");
      out.print(rs3.getString("a_text") );
      out.write("\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"container problemDetails\">\r\n");
      out.write("\t\t\t\t<div id=\"footer\" style=\"text-align:right;padding-right: 2%\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"lineFront\">\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
				}
			}
		}
	}

      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
